# Images decking should create. Use these labels for the 'decking build'
# command, or use 'all' to run all of them.
images:
  "bd4c/baseimage":        "./img/baseimage"
  "bd4c/hadoop_base":      "./img/hadoop_base"
  "bd4c/hadoop_nn":        "./img/hadoop_nn"
  "bd4c/hadoop_rm":        "./img/hadoop_rm"
  "bd4c/hadoop_snn":       "./img/hadoop_snn"
  "bd4c/hadoop_worker":    "./img/hadoop_worker"
  "bd4c/hadoop_lounge":    "./img/hadoop_lounge"
  # "bd4c/hadoop_solo":      "./img/hadoop_solo"
  "bd4c/volume_boxer":     "./img/volume_boxer"
  # "bd4c/deb_proxy":        "./img/deb_proxy"

containers: {}
clusters: {}
groups: {}
